"""Add question_type to questions

Revision ID: a3c2581f194d
Revises: e4b483e2a084
Create Date: 2025-12-15 13:58:55.393155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c2581f194d'
down_revision: Union[str, None] = 'e4b483e2a084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_type', sa.String(length=20), nullable=True))
    op.alter_column('questions', 'options',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('questions', 'correct_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'correct_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'options',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('questions', 'question_type')
    # ### end Alembic commands ###
